### ISSUE TITLE
Log all actions

### ISSUE THREAD

**Issue by lazytesting** [mirabeau-nl/WbTstr.Net#11]
Log all actions/validations which take place, this will help users to understand complex data driven tests.

**Comment by onnovalkering** [comment]
The following providers have a WbTstr wrapper that logs all actions:
- ActionSyntaxProvider
- DragDropByPositionSyntaxProvider
- DragDropSyntaxProvider
- SelectSyntaxProvider
- TextAppendSyntaxProvider
- TextEntrySyntaxProvider

Remaining providers are (at least):
- WithSyntaxProvider
- AssertSyntaxProvider (including inclass providers)

**Comment by onnovalkering** [comment]
The AssertSyntaxProvider, including inclass providers, now also logs.

**Comment by onnovalkering** [comment]
Decided is, for now, to not add logging to the WithSyntaxProvider. 
This provider is used to override some settings per ActionSyntaxProvider instance.

**Comment by lazytesting** [comment]
Closed issue as all actions are already supported, which is enough for now. If we decide that we want to add logs for the WithSyntaxProvider we'll handle that in a seperate issue.
