### ISSUE TITLE
Implement dryrun mode

### ISSUE THREAD

**Issue by lazytesting** [mirabeau-nl/WbTstr.Net#12]
For Test first development i's useful to be able to run the tests without actually invoking the browser. When a dryrun is performed we should only log the actions/validations. 
- browser should not start
- validations should always pass
- actions should not be executed

**Comment by onnovalkering** [comment]
Basic DryRun functionality has been added (no commands will be send to the webdriver, but still logs actions). Can be elaborated more in the future.
