### ISSUE TITLE
Support HTTP Basic Authentication

### ISSUE THREAD

**Issue by onnovalkering** [mirabeau-nl/WbTstr.Net#19]
We need to support HTTP basic authentication, so WbTstr can be used to access protected sites.
Possibilities include: embedding the credentials in the URL or performing an automation script (i.e. AutoIT).

**Comment by lazytesting** [comment]
Embedding in the url will give issues with some browsers as they will mark the url as malicious. I think we can use the Selenium IAlert.SetAuthenticationCredentials Method but we need to verify if it's implemented in all the major browsers.
