### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by lazytesting** [mirabeau-nl/WbTstr.Net#3]
The current code does not match with our coding standards, refactor code to match our standards. 
Where possible try to keep this as close as possible to the default ReSharper code rules as this will makes it easier to contribute.

**Comment by onnovalkering** [comment]
With possible pull requests in mind, we will not refactor Fluent code in this stage of the project. Unless it is really necessary.

The code we add as part of the WbTstr.Net project must adhere the Mirabeau coding standards.
